// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/ent-bug-edge-migration-conflict/ent/predicate"
	"github.com/lrstanley/ent-bug-edge-migration-conflict/ent/userguild"
)

// UserGuildDelete is the builder for deleting a UserGuild entity.
type UserGuildDelete struct {
	config
	hooks    []Hook
	mutation *UserGuildMutation
}

// Where appends a list predicates to the UserGuildDelete builder.
func (ugd *UserGuildDelete) Where(ps ...predicate.UserGuild) *UserGuildDelete {
	ugd.mutation.Where(ps...)
	return ugd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ugd *UserGuildDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ugd.hooks) == 0 {
		affected, err = ugd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserGuildMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ugd.mutation = mutation
			affected, err = ugd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ugd.hooks) - 1; i >= 0; i-- {
			if ugd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ugd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ugd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugd *UserGuildDelete) ExecX(ctx context.Context) int {
	n, err := ugd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ugd *UserGuildDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userguild.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userguild.FieldID,
			},
		},
	}
	if ps := ugd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ugd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserGuildDeleteOne is the builder for deleting a single UserGuild entity.
type UserGuildDeleteOne struct {
	ugd *UserGuildDelete
}

// Exec executes the deletion query.
func (ugdo *UserGuildDeleteOne) Exec(ctx context.Context) error {
	n, err := ugdo.ugd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userguild.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ugdo *UserGuildDeleteOne) ExecX(ctx context.Context) {
	ugdo.ugd.ExecX(ctx)
}
