// Code generated by ent, DO NOT EDIT.

package userguild

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lrstanley/ent-bug-edge-migration-conflict/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGuildID), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOwner), v))
	})
}

// Admin applies equality check predicate on the "admin" field. It's identical to AdminEQ.
func Admin(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdmin), v))
	})
}

// IconHash applies equality check predicate on the "icon_hash" field. It's identical to IconHashEQ.
func IconHash(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconHash), v))
	})
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconURL), v))
	})
}

// Permissions applies equality check predicate on the "permissions" field. It's identical to PermissionsEQ.
func Permissions(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPermissions), v))
	})
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateTime), v))
	})
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdateTime), v))
	})
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGuildID), v))
	})
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGuildID), v))
	})
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldGuildID), v...))
	})
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldGuildID), v...))
	})
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGuildID), v))
	})
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGuildID), v))
	})
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGuildID), v))
	})
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGuildID), v))
	})
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldGuildID), v))
	})
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldGuildID), v))
	})
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldGuildID), v))
	})
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldGuildID), v))
	})
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldGuildID), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOwner), v))
	})
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOwner), v))
	})
}

// OwnerIsNil applies the IsNil predicate on the "owner" field.
func OwnerIsNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldOwner)))
	})
}

// OwnerNotNil applies the NotNil predicate on the "owner" field.
func OwnerNotNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldOwner)))
	})
}

// AdminEQ applies the EQ predicate on the "admin" field.
func AdminEQ(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdmin), v))
	})
}

// AdminNEQ applies the NEQ predicate on the "admin" field.
func AdminNEQ(v bool) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAdmin), v))
	})
}

// AdminIsNil applies the IsNil predicate on the "admin" field.
func AdminIsNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAdmin)))
	})
}

// AdminNotNil applies the NotNil predicate on the "admin" field.
func AdminNotNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAdmin)))
	})
}

// FeaturesIsNil applies the IsNil predicate on the "features" field.
func FeaturesIsNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldFeatures)))
	})
}

// FeaturesNotNil applies the NotNil predicate on the "features" field.
func FeaturesNotNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldFeatures)))
	})
}

// IconHashEQ applies the EQ predicate on the "icon_hash" field.
func IconHashEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconHash), v))
	})
}

// IconHashNEQ applies the NEQ predicate on the "icon_hash" field.
func IconHashNEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIconHash), v))
	})
}

// IconHashIn applies the In predicate on the "icon_hash" field.
func IconHashIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldIconHash), v...))
	})
}

// IconHashNotIn applies the NotIn predicate on the "icon_hash" field.
func IconHashNotIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldIconHash), v...))
	})
}

// IconHashGT applies the GT predicate on the "icon_hash" field.
func IconHashGT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIconHash), v))
	})
}

// IconHashGTE applies the GTE predicate on the "icon_hash" field.
func IconHashGTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIconHash), v))
	})
}

// IconHashLT applies the LT predicate on the "icon_hash" field.
func IconHashLT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIconHash), v))
	})
}

// IconHashLTE applies the LTE predicate on the "icon_hash" field.
func IconHashLTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIconHash), v))
	})
}

// IconHashContains applies the Contains predicate on the "icon_hash" field.
func IconHashContains(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIconHash), v))
	})
}

// IconHashHasPrefix applies the HasPrefix predicate on the "icon_hash" field.
func IconHashHasPrefix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIconHash), v))
	})
}

// IconHashHasSuffix applies the HasSuffix predicate on the "icon_hash" field.
func IconHashHasSuffix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIconHash), v))
	})
}

// IconHashIsNil applies the IsNil predicate on the "icon_hash" field.
func IconHashIsNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIconHash)))
	})
}

// IconHashNotNil applies the NotNil predicate on the "icon_hash" field.
func IconHashNotNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIconHash)))
	})
}

// IconHashEqualFold applies the EqualFold predicate on the "icon_hash" field.
func IconHashEqualFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIconHash), v))
	})
}

// IconHashContainsFold applies the ContainsFold predicate on the "icon_hash" field.
func IconHashContainsFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIconHash), v))
	})
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconURL), v))
	})
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIconURL), v))
	})
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldIconURL), v...))
	})
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldIconURL), v...))
	})
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIconURL), v))
	})
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIconURL), v))
	})
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIconURL), v))
	})
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIconURL), v))
	})
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIconURL), v))
	})
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIconURL), v))
	})
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIconURL), v))
	})
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIconURL), v))
	})
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIconURL), v))
	})
}

// PermissionsEQ applies the EQ predicate on the "permissions" field.
func PermissionsEQ(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPermissions), v))
	})
}

// PermissionsNEQ applies the NEQ predicate on the "permissions" field.
func PermissionsNEQ(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPermissions), v))
	})
}

// PermissionsIn applies the In predicate on the "permissions" field.
func PermissionsIn(vs ...uint64) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPermissions), v...))
	})
}

// PermissionsNotIn applies the NotIn predicate on the "permissions" field.
func PermissionsNotIn(vs ...uint64) predicate.UserGuild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPermissions), v...))
	})
}

// PermissionsGT applies the GT predicate on the "permissions" field.
func PermissionsGT(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPermissions), v))
	})
}

// PermissionsGTE applies the GTE predicate on the "permissions" field.
func PermissionsGTE(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPermissions), v))
	})
}

// PermissionsLT applies the LT predicate on the "permissions" field.
func PermissionsLT(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPermissions), v))
	})
}

// PermissionsLTE applies the LTE predicate on the "permissions" field.
func PermissionsLTE(v uint64) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPermissions), v))
	})
}

// PermissionsIsNil applies the IsNil predicate on the "permissions" field.
func PermissionsIsNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPermissions)))
	})
}

// PermissionsNotNil applies the NotNil predicate on the "permissions" field.
func PermissionsNotNil() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPermissions)))
	})
}

// HasAdmins applies the HasEdge predicate on the "admins" edge.
func HasAdmins() predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AdminsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AdminsTable, AdminsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminsWith applies the HasEdge predicate on the "admins" edge with a given conditions (other predicates).
func HasAdminsWith(preds ...predicate.User) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AdminsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AdminsTable, AdminsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGuild) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGuild) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGuild) predicate.UserGuild {
	return predicate.UserGuild(func(s *sql.Selector) {
		p(s.Not())
	})
}
